Repository 404-DriverNotFound/frontend-b, pull requests merged in 2021-10, with the labels that each got.

#112 Feat: 게임 플레이 관련 기능 구현
  src/App.tsx
  src/components/atoms/List/List.tsx
  src/components/molecules/Dialog/Dialog.tsx
  src/components/molecules/GameOptionCard/GameOptionCard.stories.tsx
  src/components/molecules/GameOptionCard/GameOptionCard.tsx
  src/components/molecules/Menu/Menu.tsx
  src/components/molecules/UserProfile/UserProfile.stories.tsx
  src/components/molecules/UserProfile/UserProfile.tsx
  src/components/organisms/ChatMessage/ChatMessage.tsx
  src/components/organisms/PlayerProfile/PlayerProfile.stories.tsx
  src/components/organisms/PlayerProfile/PlayerProfile.tsx
  src/components/organisms/ProfileCard/ProfileCard.stories.tsx
  src/components/organisms/ProfileCard/ProfileCard.tsx
  src/components/pages/ChannelPage/ChannelPage.tsx
  src/components/pages/ChatPage/ChatPage.tsx
  src/components/pages/CommunityPage/CommunityPage.tsx
  src/components/pages/GamePage/GamePage.tsx
  src/components/pages/GamePlayPage/GamePage.stories.tsx
  src/components/pages/GamePlayPage/GamePlayPage.tsx
  src/components/pages/GameWatchPage/GameWatchPage.tsx
  src/components/pages/MFAPage/MFAPage.tsx
  src/components/pages/MFARegisterPage/MFARegisterPage.tsx
  src/components/pages/ProfilePage/ProfilePage.tsx
  src/types/Match.ts
  src/types/Response.ts
  src/types/User.ts
  src/utils/friendships.ts
  src/utils/game/CanvasManager.ts
  src/utils/hooks/useContext.tsx
  src/utils/hooks/useGameContext.tsx
  src/utils/hooks/useMatch.tsx
  src/utils/path.ts
  src/utils/utils.ts
Labels: enhancement

#114 Fix: Firefox에 drop-shadow 스타일 별도 적용
  src/components/molecules/GameOptionCard/GameOptionCard.tsx
  src/components/organisms/GameListItem/GameListItem.tsx
  src/components/organisms/MatchListItem/MatchListItem.tsx
Labels: bug

#116 Fix: ChatPage에서 채팅 목록을 정상적으로 로딩하지 못하는 문제 해결
  src/components/pages/ChannelManagePage/ChannelManagePage.tsx
  src/components/pages/ChannelPage/ChannelPage.tsx
  src/components/pages/ChatPage/ChatPage.tsx
  src/components/pages/CommunityPage/CommunityPage.tsx
  src/components/pages/DMPage/DMPage.tsx
  src/components/pages/GameWatchPage/GameWatchPage.tsx
  src/components/pages/ProfilePage/ProfilePage.tsx
Labels: bug

#118 Refactor: App 전체 최적화
  src/App.tsx
  src/components/atoms/Avatar/Avatar.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/ChatInput/ChatInput.tsx
  src/components/atoms/DigitInput/DigitInput.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/List/List.tsx
  src/components/atoms/ListClickItem/ListClickItem.tsx
  src/components/atoms/ListItem/ListItem.tsx
  src/components/atoms/Switch/Switch.tsx
  src/components/atoms/Typo/Typo.tsx
  src/components/molecules/Dialog/Dialog.tsx
  src/components/molecules/GameOptionCard/GameOptionCard.tsx
  src/components/molecules/Menu/Menu.tsx
  src/components/molecules/SubMenu/SubMenu.tsx
  src/components/molecules/UserProfile/UserProfile.tsx
  src/components/organisms/AchieveListItem/AchieveListItem.tsx
  src/components/organisms/ChannelInfoForm/ChannelInfoForm.tsx
  src/components/organisms/ChannelListItem/ChannelListItem.stories.tsx
  src/components/organisms/ChannelListItem/ChannelListItem.tsx
  src/components/organisms/ChannelUserListItem/ChannelUserListItem.tsx
  src/components/organisms/ChatMessage/ChatMessage.tsx
  src/components/organisms/DMListItem/DMListItem.stories.tsx
  src/components/organisms/DMListItem/DMListItem.tsx
  src/components/organisms/GameListItem/GameListItem.tsx
  src/components/organisms/MatchListItem/MatchListItem.tsx
  src/components/organisms/PlayerProfile/PlayerProfile.tsx
  src/components/organisms/ProfileCard/ProfileCard.stories.tsx
  src/components/organisms/ProfileCard/ProfileCard.tsx
  src/components/organisms/UserInfoForm/UserInfoForm.tsx
  src/components/pages/ChannelManagePage/ChannelManagePage.tsx
  src/components/pages/ChannelPage/ChannelPage.tsx
  src/components/pages/ChatPage/ChatPage.tsx
  src/components/pages/CommunityPage/CommunityPage.tsx
  src/components/pages/DMPage/DMPage.tsx
  src/components/pages/GameWatchPage/GameWatchPage.tsx
  src/components/pages/MFAPage/MFAPage.tsx
  src/components/pages/MFARegisterPage/MFARegisterPage.tsx
  src/components/pages/ProfilePage/ProfilePage.tsx
  src/components/pages/RegisterPage/RegisterPage.tsx
  src/utils/chats.ts
  src/utils/friendships.ts
  src/utils/hooks/useAppContext.tsx
  src/utils/hooks/useError.ts
  src/utils/hooks/useLogout.ts
  src/utils/hooks/useMatch.tsx
  src/utils/utils.ts
Labels: enhancement, refactoring

#124 Fix: 프로필 수정에서 아바타가 변경되지 않는 문제 해결
  src/components/organisms/UserInfoForm/UserInfoForm.tsx
Labels: bug
