Repository 404-DriverNotFound/frontend-b, pull requests merged in 2021-08, with the labels that each got.

#26 Feat: Switch Component 제작
  src/components/atoms/Switch/Switch.stories.tsx
  src/components/atoms/Switch/Switch.tsx
Labels: enhancement

#25 Feat: App 상태 관리 로직 작성
  .env
  package.json
  src/App.tsx
  src/components/pages/LoginPage/LoginPage.tsx
  src/index.tsx
  src/utils/hooks/useContext.tsx
  src/utils/utils.ts
  yarn.lock
Labels: enhancement

#34 Feat: Menu Component 제작
  src/components/molecules/Menu/Menu.stories.tsx
  src/components/molecules/Menu/Menu.tsx
Labels: enhancement

#31 Feat: 메인 페이지 Template 제작
  src/components/templates/MainTemplate/MainTemplate.stories.tsx
  src/components/templates/MainTemplate/MainTemplate.tsx
Labels: enhancement

#37 Feat: 2FA Digit input code 제작
  src/components/atoms/DigitInput/DigitInput.stories.tsx
  src/components/atoms/DigitInput/DigitInput.tsx
Labels: enhancement

#30 Feat: 회원가입 Page 제작
  src/App.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Typo/Typo.tsx
  src/components/molecules/Menu/Menu.stories.tsx
  src/components/molecules/Menu/Menu.tsx
  src/components/pages/LoginPage/LoginPage.stories.tsx
  src/components/pages/LoginPage/LoginPage.tsx
  src/components/pages/RegisterPage/RegisterPage.stories.tsx
  src/components/pages/RegisterPage/RegisterPage.tsx
  src/components/templates/MainTemplate/MainTemplate.stories.tsx
  src/utils/hooks/useContext.tsx
Labels: enhancement

#42 Feat: Dialog component 제작
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Input/Input.tsx
  src/components/molecules/Dialog/Dialog.stories.tsx
  src/components/molecules/Dialog/Dialog.tsx
Labels: enhancement

#38 Feat: List component 제작
  src/components/atoms/List/List.stories.tsx
  src/components/atoms/List/List.tsx
Labels: enhancement

#40 Feat: 2FA Page 제작
  src/App.tsx
  src/components/atoms/DigitInput/DigitInput.tsx
  src/components/pages/MFAPage/MFAPage.stories.tsx
  src/components/pages/MFAPage/MFAPage.tsx
  src/components/pages/MFARegisterPage/MFARegisterPage.stories.tsx
  src/components/pages/MFARegisterPage/MFARegisterPage.tsx
  src/components/pages/RegisterPage/RegisterPage.tsx
Labels: enhancement

#45 Feat: 회원가입 완료 시 안내 Dialog 추가
  src/App.tsx
  src/components/pages/MFARegisterPage/MFARegisterPage.tsx
  src/components/pages/RegisterPage/RegisterPage.tsx
Labels: enhancement

#44 Feat: ProfileCard component 제작
  src/components/atoms/Avatar/Avatar.tsx
  src/components/atoms/Button/Button.tsx
  src/components/molecules/UserProfile/UserProfile.stories.tsx
  src/components/molecules/UserProfile/UserProfile.tsx
  src/components/organisms/ProfileCard/ProfileCard.stories.tsx
  src/components/organisms/ProfileCard/ProfileCard.tsx
  src/types/User.ts
Labels: enhancement

#49 Fix: MFAPage, MFARegisterPage의 레이아웃이 깨지는 현상 개선
  src/components/pages/MFAPage/MFAPage.tsx
  src/components/pages/MFARegisterPage/MFARegisterPage.tsx
Labels: enhancement

#51 Refactor: 불필요한 주석 삭제 및 코드 스타일 개선
  src/components/atoms/Avatar/Avatar.stories.tsx
  src/components/atoms/Avatar/Avatar.tsx
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Input/Input.stories.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/List/List.stories.tsx
  src/components/atoms/List/List.tsx
  src/components/atoms/Switch/Switch.stories.tsx
  src/components/atoms/Switch/Switch.tsx
  src/components/atoms/Typo/Typo.stories.tsx
  src/components/atoms/Typo/Typo.tsx
  src/components/molecules/Dialog/Dialog.stories.tsx
  src/components/molecules/Dialog/Dialog.tsx
  src/components/molecules/Menu/Menu.stories.tsx
  src/components/molecules/UserProfile/UserProfile.tsx
  src/components/pages/MFAPage/MFAPage.tsx
  src/components/pages/MFARegisterPage/MFARegisterPage.tsx
  src/components/pages/RegisterPage/RegisterPage.tsx
  src/components/templates/LoginTemplate/LoginTemplate.stories.tsx
  src/components/templates/LoginTemplate/LoginTemplate.tsx
  src/components/templates/MainTemplate/MainTemplate.stories.tsx
Labels: refactoring

#52 Feat: List item component 제작#32
  src/components/atoms/List/List.stories.tsx
  src/components/atoms/List/List.tsx
  src/components/atoms/ListItem/ListItem.tsx
  src/components/atoms/ListItem/LitsItem.stories.tsx
Labels: enhancement

#57 [Feat] Community용 SubMenu 제작
  src/components/molecules/SubMenu/SubMenu.stories.tsx
  src/components/molecules/SubMenu/SubMenu.tsx
Labels: enhancement

#62 Feat: WithListAndProfileCard story추가
  src/components/atoms/ListItem/LitsItem.stories.tsx
Labels: enhancement

#64 Fix: 백엔드 로그인 로직 변경 대응
  package.json
  src/App.tsx
  src/components/molecules/Menu/Menu.tsx
  src/components/organisms/ProfileCard/ProfileCard.stories.tsx
  src/components/pages/LoginPage/LoginPage.tsx
  src/components/pages/MFAPage/MFAPage.tsx
  src/components/pages/MFARegisterPage/MFARegisterPage.tsx
  src/components/pages/RegisterPage/RegisterPage.tsx
  src/utils/hooks/useContext.tsx
  src/utils/hooks/useDialog.ts
  src/utils/utils.ts
  yarn.lock
Labels: bug, enhancement

#70 Feat: CommunityPage Component 제작
  package.json
  src/App.tsx
  src/components/organisms/ProfileCard/ProfileCard.stories.tsx
  src/components/organisms/ProfileCard/ProfileCard.tsx
  src/components/pages/CommunityPage/CommunityPage.stories.tsx
  src/components/pages/CommunityPage/CommunityPage.tsx
  src/utils/hooks/useIntersect.ts
  src/utils/utils.ts
  yarn.lock
Labels: enhancement
